---
abstract: 'Reorder GoPro files'
author:
  - 'vti <viacheslav.t@gmail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-ReorderGoProFiles
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  App::ReorderGoProFiles:
    file: lib/App/ReorderGoProFiles.pm
    version: '0.01'
requires:
  Docopt: '0'
  File::Copy: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/vti/app-reorder-gopro-files/issues
  homepage: https://github.com/vti/app-reorder-gopro-files
  repository: git://github.com/vti/app-reorder-gopro-files.git
version: '0.01'
x_authority: cpan:VTI
